apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }} 
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}  
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}  
    spec:
      containers:
        - name: {{ .Values.appName }}  
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }} 
          env:
          {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- .valueFrom | toYaml | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
          {{- end }}
          
